name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Build with Docker
      - name: Build frontend
        working-directory: ./frontend
        env:
          PUBLIC_URL: /${{ github.event.repository.name }}
        run: |
          # Build with Docker
          docker build --build-arg PUBLIC_URL=/${{ github.event.repository.name }} -t portfolio-frontend .
          docker create --name temp-container portfolio-frontend
          docker cp temp-container:/usr/share/nginx/html ../dist-frontend
          docker rm temp-container
          
          # Create .nojekyll file
          touch ../dist-frontend/.nojekyll

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist-frontend
          branch: gh-pages
          clean: true

      # Step 4: Show deployment info
      - name: Deployment info
        run: |
          echo "✅ Deployment complete!"
          echo "🔗 Site URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"